### ISSUE TITLE
Issue in Combined Elements

### ISSUE THREAD

**Issue by mobinco** [Irrelon/jquery-lang-js#134]
Hi!

Combined Elements cannot be translated correctly and repeated several times!

Example:
```
<p lang="en">Or click here to Sign up: 
  <br><a href="register"><button type="button" class="btn btn-primary btn-lg active m-t-1" lang="en">Sign Up</button></a>
</p>
```

Older version support it.

thanks

**Comment by Irrelon** [comment]
Hey, thanks for the bug report. Do you know what version it worked on? If so can you let me know and I’ll see if I can find the update that broke this. Nested elements like this are gonna be tricky to support because you have a text node in the same child level as other html nodes.

The easiest fix would be to contain your text with a span and put the lang tag on the span instead of the p tag, e.g.

```
<p><span lang=“en”>Or click here to Sign up: </span>
  <br><a href="register"><button type="button" class="btn btn-primary btn-lg active m-t-1" lang="en">Sign Up</button></a>
</p>
```

**Comment by mobinco** [comment]
I didn't find the version in the file.
But I think I used version 3. 
I got this version because of the new feature in 4.

Thanks

**Comment by Irrelon** [comment]
I'm not sure if I can identify the issue or even confirm it was working before in another version. I think the fix I proposed above is the best solution.
