### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by villanus** [Irrelon/jquery-lang-js#43]
Does this support full internationalization?  Its not only about languages, but currency codes, time / date formats, and number formats. 

How about SEO?

**Comment by Irrelon** [comment]
> Its not only about languages

Just checking if you've given the plugin a try? This is basically a token replacement engine in JavaScript. As long as you have supplied either the correct regex or correct token you can replace anything.

> How about SEO?

It depends on what you want to do with your SEO strategy but as you know JavaScript won't run in search engine spider page loads so providing a non-tokenised version of a page is a good idea. Many users have an English version of the page and translate into others (english lang becomes the tokens) so search engines see a fully readable page.

**Comment by villanus** [comment]
I did not try it directly but did have a look at sample site.   I can see where it can be useful, for example on a component for switching langues, but it seems to me for SEO value you really need different crawler accessible versions of the site.   Still might want to build in i18n, ulr routing, and hreflang meta support for those who take HTML snapshots of javascript pages.

**Comment by Irrelon** [comment]
> I did not try it directly but did have a look at sample site. I can see where it can be useful, for example on a component for switching languages, but it seems to me for SEO value you really need different crawler accessible versions of the site

The issues surrounding SEO are outside of the plugin's scope - afterall it is a JavaScript plugin so it cannot help you with how your initial HTML is sent to a client browser / spider except when you are running a modern server system like Node.js where the plugin can translate the page BEFORE it sends to the client. There are a lot of options available for ensuring that SEO is not broken by using JS to change languages, including most commonly providing a snapshot as a static page.

**Remember** that the main purpose of this plugin is to provide multi-language support for web applications that are loading dynamic content on the fly where SEO would be useless anyway because the content doesn't exist until after the user interacts with the site. In a web application you don't want to reload the page to change languages because that means reloading the entire application state.

For instance on orbzu.com we use it to display different headings on dialog boxes, buttons and other dynamically generated HTML. Switching the home-screen's language is really just the tip of the iceberg!

> Still might want to build in i18n, ulr routing, and hreflang meta support for those who take HTML snapshots of javascript pages

Not sure I follow you, could you explain a little bit more? :)

**Comment by villanus** [comment]
Totally makes sense.  Sounds like a great option when SEO is not a factor, such as an admin dashboard or webmail. 

As for HTML snapshots, its becoming common (bad practice in my opinion) to build Javascript Single Page applications where routing and dynamic content is fully handled by javascript.  Then building a web crawler to cache versions of those pages, and serving those to googlebot instead.  

Here is a site which provides it as a service:
http://www.brombone.com/

And here is an article which tells you how to setup phantom js to do it on your own.
https://vickev.com/#!/article/easily-index-your-single-page-application-thanks-to-phantomjs

So if someone wanted to use your component for a front facing site (built purely in JS) where SEO was a concern, then they would have to make the changes in the issues i brought up.  They would have to code hreflang meta tags, changing of the urls, and probably some internationalization for numbers and currency if they needed that.    Then they would use something like the service above to cache different language versions of the site based upon the pushstate urls. 

Again, you clarified that is not what the component is intended for.  Sounds like a great option for sites where SEO is not a concern such as Chat Scripts, Backend Tools, Admin Sites, etc. 

Close Issue
