### ISSUE TITLE
How to translate text nodes mixed with html nodes

### ISSUE THREAD

**Issue by rttmax** [Irrelon/jquery-lang-js#72]
In my language file i have the following token:

```
"SOME_TOKEN" : "<h2>foo</h2><p>bar</p>"
```

in my HTML: 

```
<div lang="mylang">SOME_TOKEN</div>
```

The output is plain text, not html. Is there a way to fix this?

**Comment by Irrelon** [comment]
Hmmm. At present the answer is no, but perhaps we should actually allow denoting a string as HTML rather than pure text? Maybe if we adopt a format in the lang files for HTML like:

    "SOME_TOKEN": ":html:<h2>foo</h2><p>bar</p>"

So that the plugin knows to insert HTML rather than text?

Adopting a format marker would allow for some interesting extensions to the plugin as well, in theory.

**Comment by cbje** [comment]
@rttmax @Irrelon 
I only have basic JS skills but I started a fork that can read HTML entities from the JSON here:
[https://github.com/cbje/jquery-lang-js/blob/master/js/jquery-lang.js](url)
Only limitation is that it does not correctly overwrite the original language innerHTML but I am working on it.
