### ISSUE TITLE
Hyperlink warning message

### ISSUE THREAD

**Issue by rttmax** [Irrelon/jquery-lang-js#73]
I have some links on my page which I want to translate. i.e.: 

```
<a href="#advantages" lang="translate">NAV__ADVANTAGES</a>
```

Everthing is working fine but I get the following warning on language change:

```
Translation for "#advantages" not found in language pack: de
```

How to prevent this?

**Comment by Irrelon** [comment]
The language plugin will attempt to "translate" your href as well since sometimes you might want to have your links change when the language changes.

The warning is not actually an error, it's just a programmer hint at where you might have a problem. You can totally ignore it or if it really bugs you, you can add "#advantages": "#advantages" to your langpacks.

Personally I wouldn't worry about it since it only affects developer console output.
