### ISSUE TITLE
Is it possible to add html entity to text to be translated?

### ISSUE THREAD

**Issue by internetmosquito** [Irrelon/jquery-lang-js#90]
Hi there!

First, a great thanks for jquery-lang-js, is awesome!

I'm facing the following issue...although I don't know if this is the way to call it

I have a text to be transalated like this:

```
<li lang="en" data-lang-token="copyright">Copyright &copy; 2016 Acme. All rights reserved.</li>
```

Want to translate it to spanish, so I've created this:

```
"copyright":"Copyright &copy; 2016 Acme. Todos los derechos reservados.",
```

But when translating, the html entity is not parsed, is written without the ©...

Am I missing something here or html entities are simply not allowed?

Bests,
Alejandro

**Comment by Irrelon** [comment]
Hi ya. The problem exists because the text you enter is presented on the DOM as a pure text value of the parent element, it is not parsed before being applied to the DOM.

I suppose we could try using innerHTML (.html() in jQuery) to set the inner of the parent element but I'm sure there was a reason I didn't do this, although it has been such a long time since I coded this plugin and so many other projects came after it that I cannot remember why that decision was made.

It might actually make sense to create another section of the language file so that html replacements can be made and won't affect text-only replacements.

**Comment by internetmosquito** [comment]
Okie, noted, thanks for the quick response. Is there any workaround on this that comes to mind? Maybe using the the regex section of the language file? For instance, if I detect that the sentence starts with Copyright..bla bla bla? But then, will it make a text-only replacement again?

Cheers

**Comment by Irrelon** [comment]
The regular expressions use the same text replacement system as the tokens. It is likely an easy change to allow html entities inside replacement text but I'm not in a position to look at that right now. If anyone would like to try it I'm happy to accept pull requests for such a feature.

**Comment by internetmosquito** [comment]
I understand, can you point me where to look in your code? If I have time I don't mind creating a branch and giving it a go

Cheers!

**Comment by cbje** [comment]
@internetmosquito 
I started a fork that can read HTML entities from the JSON [here](https://github.com/cbje/jquery-lang-js/blob/master/js/jquery-lang.js).
Only limitation is that it does not correctly overwrite the original language if there are innerHTML elements, but I am working on it.

**Comment by darkgnostic** [comment]
Ok, I have managed to fix it by adding 
`$(elem).html($(elem).text());`
after this line: https://github.com/Irrelon/jquery-lang-js/blob/master/js/jquery-lang.js#L503
